# Generated by Django 5.2.8 on 2026-08-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='subscription_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='yearly_subscription_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
