# Generated by Django 5.2.8 on 2026-08-23 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_siteconfig_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='admin_check',
            field=models.BooleanField(default=True, help_text='If True, verifying a scholarship applicant sends email to all users. If False, email is sent only to the applicant.', verbose_name='Admin Check'),
        ),
        migrations.CreateModel(
            name='ScholarshipApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_details', models.TextField(blank=True, default='')),
                ('admin_verified', models.BooleanField(default=False, help_text='Designates whether this applicant has been verified by admin.', verbose_name='Admin Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
