# Generated by Django 6.0.4 on 2026-05-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('yearly', 'yearly')], null=True),
        ),
    ]
