# Generated by Django 6.0.4 on 2026-07-28 10:09

import django.db.models.deletion
import movie_series.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('comming_soon_time', models.DateField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('season_name', models.TextField(db_index=True, default='')),
                ('notifyees', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProgressStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.CharField(max_length=100, unique=True)),
                ('last_position_seconds', models.IntegerField()),
                ('total_duration_seconds', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='movie_serie_slug_31aca7_idx'), models.Index(fields=['name'], name='movie_serie_name_1cf9b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('title_fr', models.CharField(db_index=True, default='', max_length=255)),
                ('title_es', models.CharField(db_index=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('description_fr', models.TextField(blank=True, default='')),
                ('description_es', models.TextField(blank=True, default='')),
                ('release_year', models.PositiveIntegerField(db_index=True, default=movie_series.models.get_default_year)),
                ('comming_soon_time', models.DateField(blank=True, null=True)),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('file_uuid', models.TextField(blank=True, null=True)),
                ('preview_gif', models.FileField(blank=True, null=True, upload_to='')),
                ('trailer', models.FileField(blank=True, null=True, upload_to=movie_series.models.get_upload_to)),
                ('posters_url', models.JSONField(blank=True, default=list)),
                ('is_popular', models.BooleanField(default=False)),
                ('premium_price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('premium_price_gourde', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('publish', models.BooleanField(default=False)),
                ('notifyees', models.JSONField(default=list)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movie_series.genre')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('title_fr', models.CharField(blank=True, default='', max_length=255)),
                ('title_es', models.CharField(blank=True, default='', max_length=255)),
                ('file_uuid', models.TextField(blank=True, null=True)),
                ('trailer', models.FileField(blank=True, null=True, upload_to=movie_series.models.get_upload_to)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie_series.season')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name_fr', models.CharField(db_index=True, default='', max_length=255)),
                ('name_es', models.CharField(db_index=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('description_fr', models.TextField(blank=True, default='')),
                ('description_es', models.TextField(blank=True, default='')),
                ('premium_price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('premium_price_gourde', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_popular', models.BooleanField(default=False)),
                ('posters_url', models.JSONField(blank=True, default=list)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('genres', models.ManyToManyField(blank=True, related_name='series_set', to='movie_series.genre')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie_series.series'),
        ),
        migrations.CreateModel(
            name='PremiumCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ManyToManyField(blank=True, to='movie_series.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_collection', to=settings.AUTH_USER_MODEL)),
                ('series', models.ManyToManyField(blank=True, to='movie_series.series')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes', models.ManyToManyField(blank=True, to='movie_series.episode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('movies', models.ManyToManyField(blank=True, to='movie_series.movie')),
                ('series', models.ManyToManyField(blank=True, to='movie_series.series')),
            ],
        ),
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('episodes', models.ManyToManyField(blank=True, to='movie_series.episode')),
                ('movies', models.ManyToManyField(blank=True, to='movie_series.movie')),
                ('series', models.ManyToManyField(blank=True, to='movie_series.series')),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ManyToManyField(blank=True, to='movie_series.movie')),
                ('series', models.ManyToManyField(blank=True, to='movie_series.series')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ManyToManyField(to='movie_series.movie')),
                ('series', models.ManyToManyField(to='movie_series.series')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_later', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_year'], name='movie_serie_release_ce50e8_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movie_serie_title_2fe2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-created_at'], name='movie_serie_user_id_25f68f_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season'], name='movie_serie_season__ab5879_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'title')},
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['name'], name='movie_serie_name_472b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['series', 'season_name'], name='movie_serie_series__9fa5e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'season_name')},
        ),
    ]
