# Generated by Django 5.2.8 on 2026-08-18 04:36

import movie_series.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.ImageField(blank=True, null=True, upload_to=movie_series.models.get_upload_to),
        ),
    ]
